---
application:
  name: "aria2c-ariang"
  project: "Asdf1"
  organization: "QoveryCommunity"
routers:
- name: "main-aria2c-ariang"
  routes:
  - application_name: "aria2c-ariang"
    paths:
    - "/*"
